:docs: https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/

= Spring Boot 1.3.0 M5 Release Notes
For changes in earlier milestones, please refer to:

 - link:Spring-Boot-1.3.0-M1-Release-Notes[v1.3.0 M1]
 - link:Spring-Boot-1.3.0-M2-Release-Notes[v1.3.0 M2]
 - link:Spring-Boot-1.3.0-M3-Release-Notes[v1.3.0 M3]
 - link:Spring-Boot-1.3.0-M4-Release-Notes[v1.3.0 M4]

== Upgrading
No special steps are required to upgrade from earlier Spring Boot 1.3 milestones. See https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.3.0-M1-Release-Notes#upgrading-from-spring-boot-12[the instructions in the M1 release notes] for upgrade from 1.2.x.

=== Exception logging
By default Spring Boot will now log the root cause of an exception first instead of the standard "root cause last". If you prefer the root cause to be last you can either set `logging.exception.conversion.word=wex` in your `application.properties` or use custom logging configuration.

=== Tomcat RemoteIpValve
Tomcat's `RemoteIpValve` is now configured and enabled to support `x-forwarded-for` and `x-forwarded-proto` headers. If you want to disable `RemoteIpValve` set `server.tomcat.remote-ip-header` and `server.tomcat.protocol-header` to empty strings.

=== Deprecations in Spring Boot 1.3.0 M5
* `Log4JLoggingSystem` is now deprecated following Apache's https://blogs.apache.org/foundation/entry/apache_logging_services_project_announces[EOL declaration for log4j 1.x].

== New and Noteworthy
TIP: Check link:Spring-Boot-1.3.0-M5-Configuration-Changelog[the configuration changelog] for a complete overview of the changes in configuration.

=== Support for @WebServlet, @WebFilter, and @WebListener
When using an embedded servlet container, automatic registration of `@WebServlet`, `@WebFilter`, and `@WebListener` annotated classes can now be enabled using `@ServletComponentScan`.

=== Hazelcast auto-configuration
Auto-configuration is now provided for Hazelcast.

=== Miscellaneous
* Property binding failures now include better exception messages.
* The `@SpringBootApplication` annotation now includes `scanBasePackages` and `scanBasePackageClasses` attributes.
* New `AllNestedConditions` and `NoneNestedConditions` are provided (similar to the existing `AnyNestedCondition`)
