:docs: https://docs.spring.io/spring-boot/docs/2.2.x-SNAPSHOT/reference/html

= Spring Boot 2.2.0 M6 Release Notes

For changes in earlier milestones, please refer to:

 - link:Spring-Boot-2.2.0-M5-Release-Notes[v2.2.0 M5]
 - link:Spring-Boot-2.2.0-M4-Release-Notes[v2.2.0 M4]
 - link:Spring-Boot-2.2.0-M3-Release-Notes[v2.2.0 M3]
 - link:Spring-Boot-2.2.0-M2-Release-Notes[v2.2.0 M2]
 - link:Spring-Boot-2.2.0-M1-Release-Notes[v2.2.0 M1]



== Upgrading from Spring Boot 2.1
See instructions in the link:Spring-Boot-2.2.0-M1-Release-Notes[2.2.0.M1 release notes] for upgrading from Spring Boot 2.1.



=== Health Indicator
A number of classes have been deprecated to implement the new health indicator groups feature. If you are configuring a custom `HealthIndicator` via `CompositeHealthIndicatorConfiguration`, you'll need to update it to use `CompositeHealthContributorConfiguration` instead.




== New and Noteworthy
TIP: Check link:Spring-Boot-2.2.0-M6-Configuration-Changelog[the configuration changelog] for a complete overview of the changes in configuration. 


=== Health Indicator Groups
It is now possible to organize health indicators into groups. A typical example if you deploy your application to Kubernetes, you may want one different sets of health indicators for your “liveness” and “readiness” probes.

Groups can be configured via configuration properties. The following create a `custom` group with only the `DataSource` indicator:

[source,properties]
----
management.endpoint.health.group.custom.include=db
----

The `custom` group can be invoked by hitting `localhost:8080/actuator/health/custom`.

Check the {docs}/production-ready-features.html#health-groups[updated reference documentation] for more details.

=== Auto-configuration for Flyway JavaMigrations

Flyway will be auto-configured to use any `JavaMigration` beans that are found in the application context.

=== Sanitization of URI Properties in Actuator Endpoints

The sanitization performed by the `configprops` and `env` endpoints has been improved to include URI properties. Any password found in the URI's user information will now be sanitized.

=== Dependency Upgrades
Spring Boot 2.2.0.M6 moves to new versions of several Spring projects:

- Spring Framework 5.2.0.RC2
- Reactor Dysprosium-RC1
- Spring AMQP 2.2.0.RC1
- Spring Data Moore-RC3
- Spring Integration 5.2.0.RC1
- Spring Kafka 2.3.0.RC1
- Spring Security 5.2.0.RC1
- Spring Session Corn-M4

Numerous third-party dependencies have also been updated, some of the more noteworthy of which are the following:

- Flyway 6.0.1
- Kotlin 1.3.50
- Git commit id plugin 3.0.1


=== Miscellaneous

In addition to the changes listed above, there have also been lots of minor tweaks and improvements including:

- Configurable timeout for JMS listener container's receive
- Support for Spring Session's flush mode
- Support for Spring AMQP's `confirm-type`
- Application properties for configuring Jetty's thread pool
- Support for parallel test execution when using @AutoConfigureMockMvc with JUnit 5


== Deprecations in Spring Boot 2.2.0 M6
- `ApplicationHealthIndicator` in favour of `PingHealthIndicator` that is always contributed