:docs: https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/

= Spring Boot 1.3.0 M4 Release Notes
For changes in earlier milestones, please refer to:

 - link:Spring-Boot-1.3.0-M1-Release-Notes[v1.3.0 M1]
 - link:Spring-Boot-1.3.0-M2-Release-Notes[v1.3.0 M2]
 - link:Spring-Boot-1.3.0-M3-Release-Notes[v1.3.0 M3]

== Upgrading
No special steps are required to upgrade from earlier Spring Boot 1.3 milestones. See https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.3.0-M1-Release-Notes#upgrading-from-spring-boot-12[the instructions in the M1 release notes] for upgrade from 1.2.x.

=== Cloudfoundry deployment regression
Unfortunately, `1.3.0.M3` contains a https://github.com/spring-projects/spring-boot/issues/3745[property binding regression] that prevents deployment of a Spring Boot application to CloudFoundry. This regression has been fixed.

=== H2 auto-configuration
The H2 auto-configuration feature introduced in `1.3.0.M3` was not enabled properly when `spring-boot-devtools` is available on the classpath. This has been fixed.

== New and Noteworthy
TIP: Check link:Spring-Boot-1.3.0-M4-Configuration-Changelog[the configuration changelog] for a complete overview of the changes in configuration.

=== DataSource type
The connection pool used by auto-configuration can now be specified via the `spring.datasource.type` configuration key.

=== Internationalization
The `fallbackToSystemLocale` flag of the auto-configured `MessageSource` instance can now be configured via the `spring.messages.fallback-to-system-locale- configuration key.
